### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by Snarf42** [karnpapon/oscd#3]
both are valid messages to QLab

> /cue/selected/level/0/1/- 2
[SUCCESS]: packets = ("/cue/selected/level/0/1/-", [Int(2)])
> /cue/selected/level/0/1/+ 2
[ERROR]: parsing msg [Error(24..27, "Unexpected: `+ 2`")]

**Comment by karnpapon** [comment]
thanks for bringing this up! I'll take a closer look soon. From a quick glance, it seems there might be a minor issue with the parsing that needs adjustment.

**Comment by karnpapon** [comment]
fixed in (bc7cad719c). 

Currently, it allows sending OSC addresses with wildcard like `/cue/selected/level/0/1/*` or `/cue/selected/level/0/1/+` etc, but it also doesn't block invalid addresses such as `//` or `/cue///level/0/1//`. Handling all edge cases for valid and invalid OSC addresses would be an ideal but require significant effort (just learning `nom` anyway), so I’m leaving it as is for now, might revisit again soon or in case anyone open PR is welcome.
